from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import InternshipPlacementViewSet

# Create router and register the viewset
router = DefaultRouter()
router.register(r'placements', InternshipPlacementViewSet, basename='placement')

urlpatterns = [
    # All viewset routes are automatically generated by DefaultRouter
    path('', include(router.urls)),
]